services:
  webapi:
    image: ${DOCKER_REGISTRY-}mapbd
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=db;Database=mapbd;User=SA;Password=password_123;TrustServerCertificate=True;MultipleActiveResultSets=true
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=password_123"
      - "ACCEPT_EULA=Y"
    container_name: mssql
    ports:
      - "1433:1433"